version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_HOST_AUTH_METHOD: trust

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_DATABASE: your_database
        MONGO_INITDB_ROOT_USERNAME: your_username
        MONGO_INITDB_ROOT_PASSWORD: your_password
